import 'package:flutter/material.dart';

final List<Map<String, dynamic>> stadiums = [
  {
    'name': 'Al-Siteen Stadium',
    'price': '2000 YER/hour',
    'image': 'assets/images/stadiums/1.png',
    'capacity': 9,
    'location': 'mukalla',
    'startDate': TimeOfDay(hour: 10, minute: 30),
    'endDate': TimeOfDay(hour: 24, minute: 00),
    'isFavorite': false,
  },
  {
    'name': 'Al-Amoudi Stadium',
    'price': '2000 YER/hour',
    'image': 'assets/images/stadiums/2.png',
    'capacity': 11,
    'location': 'mukalla',
    'startDate': TimeOfDay(hour: 10, minute: 30),
    'endDate': TimeOfDay(hour: 24, minute: 00),
    'isFavorite': false,
  },
  {
    'name': 'Al-Shafei Stadium',
    'price': '2000 YER/hour',
    'image': 'assets/images/stadiums/3.png',
    'capacity': 8,
    'location': 'Al-Shafei',
    'startDate': TimeOfDay(hour: 10, minute: 30),
    'endDate': TimeOfDay(hour: 24, minute: 00),
    'isFavorite': false,
  },
  {
    'name': 'Al-Bander Stadium',
    'price': '2000 YER/hour',
    'image': 'assets/images/stadiums/4.png',
    'capacity': 9,
    'location': 'mukalla',
    'startDate': TimeOfDay(hour: 10, minute: 30),
    'endDate': TimeOfDay(hour: 24, minute: 00),
    'isFavorite': false,
  },
  {
    'name': 'Al-Monash Stadium',
    'price': '2000 YER/hour',
    'image': 'assets/images/stadiums/5.png',
    'capacity': 7,
    'location': 'Fowah',
    'startDate': TimeOfDay(hour: 10, minute: 30),
    'endDate': TimeOfDay(hour: 24, minute: 00),
    'isFavorite': false,
  },
  {
    'name': 'Al-Amoudi Stadium',
    'price': '2000 YER/hour',
    'image': 'assets/images/stadiums/6.png',
    'capacity': 11,
    'location': 'mukalla',
    'startDate': TimeOfDay(hour: 8, minute: 30),
    'endDate': TimeOfDay(hour: 9, minute: 30),
    'isFavorite': false,
  },
];
